// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HotelsDbContext))]
    [Migration("20260110002111_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Booking", b =>
            {
                b.Property<int>("BookingId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                b.Property<string>("BookingReference")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Cancelled")
                    .HasColumnType("bit");

                b.Property<int>("Customer_Id")
                    .HasColumnType("int");

                b.Property<double>("TotalPrice")
                    .HasColumnType("float");

                b.HasKey("BookingId");

                b.HasIndex("Customer_Id");

                b.ToTable("Bookings");
            });

            modelBuilder.Entity("DataAccess.Customer", b =>
            {
                b.Property<int>("CustomerId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CustomerId");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("DataAccess.GuestBooking", b =>
            {
                b.Property<int>("GuestBookingId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestBookingId"));

                b.Property<int>("GuestId")
                    .HasColumnType("int");

                b.Property<int>("RoomBooking_Id")
                    .HasColumnType("int");

                b.HasKey("GuestBookingId");

                b.HasIndex("GuestId");

                b.HasIndex("RoomBooking_Id");

                b.ToTable("GuestBookings");
            });

            modelBuilder.Entity("DataAccess.Hotel", b =>
            {
                b.Property<int>("HotelId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("HotelId");

                b.ToTable("Hotels");
            });

            modelBuilder.Entity("DataAccess.Payment", b =>
            {
                b.Property<int>("PaymentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                b.Property<double>("Amount")
                    .HasColumnType("float");

                b.Property<int>("Booking_Id")
                    .HasColumnType("int");

                b.Property<DateTime>("PaymentDate")
                    .HasColumnType("datetime2");

                b.Property<string>("PaymentMethod")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("PaymentId");

                b.ToTable("Payments");
            });

            modelBuilder.Entity("DataAccess.Room", b =>
            {
                b.Property<int>("RoomId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<int>("Hotel_Id")
                    .HasColumnType("int");

                b.Property<double>("PricePerNight")
                    .HasColumnType("float");

                b.Property<int>("RoomNumber")
                    .HasColumnType("int");

                b.Property<int>("RoomTypeId")
                    .HasColumnType("int");

                b.HasKey("RoomId");

                b.HasIndex("Hotel_Id");

                b.ToTable("Rooms");
            });

            modelBuilder.Entity("DataAccess.RoomBooking", b =>
            {
                b.Property<int>("RoomBookingId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomBookingId"));

                b.Property<int>("Booking_Id")
                    .HasColumnType("int");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Room_Id")
                    .HasColumnType("int");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.HasKey("RoomBookingId");

                b.HasIndex("Booking_Id");

                b.HasIndex("Room_Id");

                b.ToTable("RoomBookings");
            });

            modelBuilder.Entity("DataAccess.Booking", b =>
            {
                b.HasOne("DataAccess.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("Customer_Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");
            });

            modelBuilder.Entity("DataAccess.GuestBooking", b =>
            {
                b.HasOne("DataAccess.Customer", "Guest")
                    .WithMany()
                    .HasForeignKey("GuestId")
                    .OnDelete(DeleteBehavior.ClientNoAction)
                    .IsRequired();

                b.HasOne("DataAccess.RoomBooking", "RoomBooking")
                    .WithMany("GuestBookings")
                    .HasForeignKey("RoomBooking_Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Guest");

                b.Navigation("RoomBooking");
            });

            modelBuilder.Entity("DataAccess.Room", b =>
            {
                b.HasOne("DataAccess.Hotel", "Hotel")
                    .WithMany("Rooms")
                    .HasForeignKey("Hotel_Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Hotel");
            });

            modelBuilder.Entity("DataAccess.RoomBooking", b =>
            {
                b.HasOne("DataAccess.Booking", "Booking")
                    .WithMany("RoomBookings")
                    .HasForeignKey("Booking_Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DataAccess.Room", "Room")
                    .WithMany("RoomBookings")
                    .HasForeignKey("Room_Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Booking");

                b.Navigation("Room");
            });

            modelBuilder.Entity("DataAccess.Booking", b =>
            {
                b.Navigation("RoomBookings");
            });

            modelBuilder.Entity("DataAccess.Hotel", b =>
            {
                b.Navigation("Rooms");
            });

            modelBuilder.Entity("DataAccess.Room", b =>
            {
                b.Navigation("RoomBookings");
            });

            modelBuilder.Entity("DataAccess.RoomBooking", b =>
            {
                b.Navigation("GuestBookings");
            });
#pragma warning restore 612, 618

        }
    }
}
